import User1 from '../assets/images/user/gilbert.png';
import User2 from '../assets/images/user/user-02.png';
import User3 from '../assets/images/user/user-01.png';
import User4 from '../assets/images/user/user-04.png';

const DataShowSpot = [
  {
    id: 1,
    namaPegawai: 'Gilbert Hutapea',
    photo: <img src={User1} alt="Gilbert Hutapea" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Morning',
  },
  {
    id: 2,
    namaPegawai: 'Layla Siregar',
    photo: <img src={User2} alt="Layla Siregar" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web A',
    hakAkses: 'Afternoon',
  },
  {
    id: 3,
    namaPegawai: 'Zilong Sibarani',
    photo: <img src={User3} alt="Zilong Sibarani" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Night',
  },
  {
    id: 4,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User4} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web B',
    hakAkses: 'Morning',
  },
  {
    id: 5,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User3} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Afternoon',
  },
  {
    id: 6,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User2} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web C',
    hakAkses: 'Night',
  },
  {
    id: 7,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User1} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Morning',
  },
  {
    id: 8,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User4} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web A',
    hakAkses: 'Afternoon',
  },
  {
    id: 9,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User2} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Night',
  },
  {
    id: 10,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User3} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web B',
    hakAkses: 'Morning',
  },
  {
    id: 11,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User4} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Afternoon',
  },
  {
    id: 12,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User1} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web C',
    hakAkses: 'Night',
  },
  {
    id: 13,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User4} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Morning',
  },
  {
    id: 14,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User3} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web A',
    hakAkses: 'Afternoon',
  },
  {
    id: 15,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User2} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Night',
  },
  {
    id: 16,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User1} alt="Nana Silaban" />,
    jenisKelamin: 'Bandung Institute of Technology',
    tanggalMasuk: 'Information Systems',
    status: 'Web B',
    hakAkses: 'Morning',
  },
  {
    id: 17,
    namaPegawai: 'Nana Silaban',
    photo: <img src={User2} alt="Nana Silaban" />,
    jenisKelamin: 'University of Indonesia',
    tanggalMasuk: 'Informatics Engineering',
    status: 'Mobile',
    hakAkses: 'Afternoon',
  },
];

export default DataShowSpot;
